### ISSUE TITLE
Feature Request: Port/Add Description

### ISSUE THREAD

**Issue by migbro** [brentp/echtvar#33]
Hi! I've been creating a reference of my own, and I noticed that the INFO Description from the source VCF is not carried over when I use an alias in the config (I haven't tried no alias). Would it be possible to use the original corresponding `##INFO` header entry (aside from alias for `ID`) or to be able to specify in config (so like `e.description`)? I believe it can happen here: https://github.com/brentp/echtvar/blob/main/src/lib/echtvar.rs#L176-L194. I think it'd' also be good to keep/specify `Number` so as to comply with proper VCF specs. Thanks in advance!

**Comment by brentp** [comment]
I like this idea!
Definitely open to a PR that implements this. It will have to modify the [encoder command](https://github.com/brentp/echtvar/blob/main/src/commands/encoder_cmd.rs) and extract the description there and save it to the archive.
I'll try to get around to implementing this, but it's not high on my priority list due to time limitations.

**Comment by migbro** [comment]
This was solved by PR #34  and PR #35 .Thanks for the help and review!
